// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any
    environment {
        // Ensures HOME is set for known_hosts & SSH
        HOME = '/var/lib/jenkins'
    }
    stages {
        stage('Prepare SSH') {
            steps {
                sh '''
                    mkdir -p $HOME/.ssh
                    ssh-keyscan github.com >> $HOME/.ssh/known_hosts
                    chmod 600 $HOME/.ssh/known_hosts
                '''
            }
        }
        stage('Backup Dockerfile') {
            steps {
                sh 'chmod +x backup-scripts/backup_dockerfile.sh'
                sh './backup-scripts/backup_dockerfile.sh'
            }
        }
        stage('Build and Run App') {
            steps {
                echo 'Build or run app commands go here'
            }
        }
    }
}
