// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any
    stages {
        stage('Backup Dockerfile') {
            steps {
                sh 'chmod +x backup_dockerfile.sh'
                sh './backup_dockerfile.sh'
            }
        }
        stage('Update/Deploy') {
            steps {
                echo '...do your update steps here...'
            }
        }
    }
}
