# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
set -e

DOCKERFILE_PATH="./Dockerfile"
BACKUP_DIR="./dockerfile-backups"
BACKUP_REPO="git@github.com:komalgt/dockerfile-backups.git"

if [ ! -d "$BACKUP_DIR/.git" ]; then
    git clone "$BACKUP_REPO" "$BACKUP_DIR"
fi

cd "$BACKUP_DIR"
git pull

TIMESTAMP=$(date +"%Y%m%d-%H%M")
cp "$DOCKERFILE_PATH" "Dockerfile.backup.$TIMESTAMP"

git add "Dockerfile.backup.$TIMESTAMP"
git config user.name "Jenkins Backup"
git config user.email "jenkins-bot@example.com"
git commit -m "Backup Dockerfile at $TIMESTAMP"
git push
cd -
