# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash

# ==== USER CONFIG ====
DOCKERFILE_PATH="./Dockerfile"
BACKUP_DIR="./dockerfile-backups"
BACKUP_REPO="git@github.com:yourorg/dockerfile-backups.git"

# ==== CLONE OR PULL BACKUP REPO ====
if [ -d "$BACKUP_DIR/.git" ]; then
    cd "$BACKUP_DIR"
    git pull
else
    git clone "$BACKUP_REPO" "$BACKUP_DIR"
    cd "$BACKUP_DIR"
fi

# ==== BACKUP THE DOCKERFILE ====
TIMESTAMP=$(date +"%Y%m%d-%H%M")
cp "$DOCKERFILE_PATH" "Dockerfile.backup.$TIMESTAMP"

# ==== COMMIT AND PUSH ====
git add "Dockerfile.backup.$TIMESTAMP"
git commit -m "Backup Dockerfile at $TIMESTAMP"
git push
